name: Marketplace Watch → Telegram

on:
  schedule:
    - cron: "0 7 * * *"   # 07:00 UTC ≈ 09:00 MSK/Берлин (подправь при желании)
  workflow_dispatch: {}

permissions:
  contents: write    # чтобы коммитить data/last_hash.json

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml cloudscraper

      - name: Run watcher
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scripts/watch_marketplaces.py

      - name: Commit state (hashes)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/last_hash.json
            git commit -m "chore(watch): update last_hash.json"
            git push
          fi
